/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sab_grafika;

import javax.swing.JFrame;
import sab_implementacija.Apartman;
import sab_implementacija.Kupac;
import sab_implementacija.Prodavac;

/**
 *
 * @author Marija
 */
public class DodajApartman extends javax.swing.JPanel {

    private SAB_Projekat Home;

    /**
     * Creates new form RegistracijaKupca
     */
    public DodajApartman(SAB_Projekat Home) {
        initComponents();
        this.Home = Home;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Naziv = new javax.swing.JTextField();
        Grad = new javax.swing.JTextField();
        UlicaIBroj = new javax.swing.JTextField();
        Opis = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DodajApartman = new javax.swing.JButton();
        Drzava = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(1600, 600));

        Naziv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NazivActionPerformed(evt);
            }
        });

        Grad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradActionPerformed(evt);
            }
        });

        UlicaIBroj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UlicaIBrojActionPerformed(evt);
            }
        });

        Opis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpisActionPerformed(evt);
            }
        });

        jLabel1.setText("Naziv");

        jLabel2.setText("Drzava");

        jLabel3.setText("Grad");

        jLabel4.setText("Ulica i broj");

        jLabel5.setText("Opis");

        DodajApartman.setText("Dodaj apartman");
        DodajApartman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DodajApartmanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DodajApartman)
                    .addComponent(Opis)
                    .addComponent(UlicaIBroj)
                    .addComponent(Grad)
                    .addComponent(Naziv, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(Drzava))
                .addContainerGap(1300, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Naziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Drzava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Grad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UlicaIBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Opis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 308, Short.MAX_VALUE)
                .addComponent(DodajApartman)
                .addGap(70, 70, 70))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DodajApartmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DodajApartmanActionPerformed

         Apartman.dodajApartman(Naziv.getText(), Drzava.getText(), Grad.getText(), UlicaIBroj.getText(), Opis.getText(), Prodavac.getID());
          this.Home.Switch(new PretragaApartmanaProdavac(this.Home));
         
    }//GEN-LAST:event_DodajApartmanActionPerformed

    private void GradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GradActionPerformed

    private void UlicaIBrojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UlicaIBrojActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UlicaIBrojActionPerformed

    private void OpisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpisActionPerformed

    private void NazivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NazivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NazivActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DodajApartman;
    private javax.swing.JTextField Drzava;
    private javax.swing.JTextField Grad;
    private javax.swing.JTextField Naziv;
    private javax.swing.JTextField Opis;
    private javax.swing.JTextField UlicaIBroj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
