/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sab_grafika;

import sab_implementacija.Kupac;
import sab_implementacija.Prodavac;

/**
 *
 * @author Marija
 */
public class LoginProdavca extends javax.swing.JPanel {
    
    private SAB_Projekat Home;

    /**
     * Creates new form LoginKupca
     */
    public LoginProdavca(SAB_Projekat Home) {
        initComponents();
        this.Home = Home;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        KorisnickoIme = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Prijava = new javax.swing.JButton();
        Lozinka = new javax.swing.JPasswordField();

        KorisnickoIme.setText("jTextField1");

        jLabel1.setText("Korisnicko ime");

        jLabel2.setText("Lozinka");

        Prijava.setText("Prijavi se");
        Prijava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrijavaActionPerformed(evt);
            }
        });

        Lozinka.setText("jPasswordField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Prijava)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lozinka, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(KorisnickoIme))
                        .addGap(66, 66, 66))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Lozinka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(Prijava)
                .addContainerGap(77, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PrijavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrijavaActionPerformed
        if (Prodavac.prijavljivanjeProdavca(this.KorisnickoIme.getText(), this.Lozinka.getText())) {
            Prodavac.setID(Prodavac.dohvatiIDProdavca(this.KorisnickoIme.getText()));
            Prodavac.setUlogovan(true);
            this.Home.Switch(new PretragaApartmanaLokacija(this.Home));
            
            this.Home.getMojProfil().setVisible(true);
            this.Home.getMojProfilProdavac().setVisible(true);
            this.Home.getProdavacB().setVisible(true);
            this.Home.getOdjavljivanje().setVisible(true);
            
            this.Home.getLogin().setVisible(false);
            this.Home.getRegistracija().setVisible(false);
            this.Home.getMojProfilKupac().setVisible(false);
            this.Home.getKupacB().setVisible(false);
        } else {
            this.Home.Switch(new RegistracijaProdavca(this.Home));
        }
    }//GEN-LAST:event_PrijavaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField KorisnickoIme;
    private javax.swing.JPasswordField Lozinka;
    private javax.swing.JButton Prijava;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
