/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sab_grafika;

import javax.swing.JFrame;

/**
 *
 * @author Marija
 */
public class Odjavljivanje extends javax.swing.JPanel {
       private SAB_Projekat Home;
    /**
     * Creates new form Odjavljivanje
     */
    public Odjavljivanje(SAB_Projekat Home) {
        initComponents();
        this.Home = Home;
        
        this.Home.getLogin().setVisible(true);
        this.Home.getRegistracija().setVisible(true);
        
   
        this.Home.getMojProfil().setVisible(false);
        this.Home.getProdavacB().setVisible(false);
        this.Home.getKupacB().setVisible(false);
        this.Home.getOdjavljivanje().setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1600, 600));
        setPreferredSize(new java.awt.Dimension(1600, 600));

        jLabel1.setText("Dovidjenja !");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel1)
                .addContainerGap(1368, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel1)
                .addContainerGap(443, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
