/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sab_grafika;

import java.awt.CardLayout;
import java.awt.Label;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import sab_implementacija.Kupac;
import sab_implementacija.Prodavac;

/**
 *
 * @author Marija
 */
public class SAB_Projekat extends javax.swing.JFrame {

    /**
     * Creates new form SAB_Projekat
     */
    public SAB_Projekat() {
        initComponents();

        this.MojProfil.setVisible(false);
        this.ProdavacB.setVisible(false);
        this.KupacB.setVisible(false);
        this.Odjavljivanje.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        HomePanel = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jMenuBar1 = new javax.swing.JMenuBar();
        Login = new javax.swing.JMenu();
        LoginKupac = new javax.swing.JMenuItem();
        LoginProdavac = new javax.swing.JMenuItem();
        Registracija = new javax.swing.JMenu();
        RegistracijaKupac = new javax.swing.JMenuItem();
        RegistracijaProdavac = new javax.swing.JMenuItem();
        MojProfil = new javax.swing.JMenu();
        MojProfilKupac = new javax.swing.JMenuItem();
        MojProfilProdavac = new javax.swing.JMenuItem();
        ProdavacB = new javax.swing.JMenu();
        MojiApartmani = new javax.swing.JMenuItem();
        MojeRezervacijeProdavac = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        ApartmaniLokacijaProdavac = new javax.swing.JMenuItem();
        KupacB = new javax.swing.JMenu();
        MojeRezervacijeKupac = new javax.swing.JMenuItem();
        ApartmaniLokacijaKupac = new javax.swing.JMenuItem();
        Odjavljivanje = new javax.swing.JMenu();
        Odjava = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        HomePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 153, 153)));
        HomePanel.setMinimumSize(new java.awt.Dimension(1600, 600));
        HomePanel.setPreferredSize(new java.awt.Dimension(1600, 600));

        label1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        label1.setText("SAB_Projekat");

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1287, Short.MAX_VALUE))
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(863, Short.MAX_VALUE))
        );

        getContentPane().add(HomePanel);

        Login.setText("Logovanje");

        LoginKupac.setText("Kupac");
        LoginKupac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginKupacActionPerformed(evt);
            }
        });
        Login.add(LoginKupac);

        LoginProdavac.setText("Prodavac");
        LoginProdavac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginProdavacActionPerformed(evt);
            }
        });
        Login.add(LoginProdavac);

        jMenuBar1.add(Login);

        Registracija.setText("Registracija");

        RegistracijaKupac.setText("Kupac");
        RegistracijaKupac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistracijaKupacActionPerformed(evt);
            }
        });
        Registracija.add(RegistracijaKupac);

        RegistracijaProdavac.setText("Prodavac");
        RegistracijaProdavac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistracijaProdavacActionPerformed(evt);
            }
        });
        Registracija.add(RegistracijaProdavac);

        jMenuBar1.add(Registracija);

        MojProfil.setText("Moj profil");

        MojProfilKupac.setText("Kupac");
        MojProfilKupac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MojProfilKupacActionPerformed(evt);
            }
        });
        MojProfil.add(MojProfilKupac);

        MojProfilProdavac.setText("Prodavac");
        MojProfilProdavac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MojProfilProdavacActionPerformed(evt);
            }
        });
        MojProfil.add(MojProfilProdavac);

        jMenuBar1.add(MojProfil);

        ProdavacB.setText("Prodavac");

        MojiApartmani.setText("Moji apartmani");
        MojiApartmani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MojiApartmaniActionPerformed(evt);
            }
        });
        ProdavacB.add(MojiApartmani);

        MojeRezervacijeProdavac.setText("Moje rezervacije");
        MojeRezervacijeProdavac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MojeRezervacijeProdavacActionPerformed(evt);
            }
        });
        ProdavacB.add(MojeRezervacijeProdavac);

        jMenuItem7.setText("Dodaj apartman");
        ProdavacB.add(jMenuItem7);

        ApartmaniLokacijaProdavac.setText("Pretraga ");
        ApartmaniLokacijaProdavac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApartmaniLokacijaProdavacActionPerformed(evt);
            }
        });
        ProdavacB.add(ApartmaniLokacijaProdavac);

        jMenuBar1.add(ProdavacB);

        KupacB.setText("Kupac");

        MojeRezervacijeKupac.setText("Moje rezervacije");
        MojeRezervacijeKupac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MojeRezervacijeKupacActionPerformed(evt);
            }
        });
        KupacB.add(MojeRezervacijeKupac);

        ApartmaniLokacijaKupac.setText("Pretraga");
        ApartmaniLokacijaKupac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApartmaniLokacijaKupacActionPerformed(evt);
            }
        });
        KupacB.add(ApartmaniLokacijaKupac);

        jMenuBar1.add(KupacB);

        Odjavljivanje.setText("Odjavi se");

        Odjava.setText("Odjavi se");
        Odjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OdjavaActionPerformed(evt);
            }
        });
        Odjavljivanje.add(Odjava);

        jMenuBar1.add(Odjavljivanje);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistracijaProdavacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistracijaProdavacActionPerformed

        Switch(new RegistracijaProdavca(this));
    }//GEN-LAST:event_RegistracijaProdavacActionPerformed

    private void RegistracijaKupacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistracijaKupacActionPerformed

        Switch(new RegistracijaKupca(this));
    }//GEN-LAST:event_RegistracijaKupacActionPerformed

    private void MojProfilKupacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MojProfilKupacActionPerformed
        Switch(new MojProfilKupac(this));
    }//GEN-LAST:event_MojProfilKupacActionPerformed

    private void LoginProdavacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginProdavacActionPerformed
        Switch(new LoginProdavca(this));
    }//GEN-LAST:event_LoginProdavacActionPerformed

    private void LoginKupacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginKupacActionPerformed
        Switch(new LoginKupca(this));

    }//GEN-LAST:event_LoginKupacActionPerformed

    private void MojProfilProdavacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MojProfilProdavacActionPerformed
        Switch(new MojProfilProdavac(this));
    }//GEN-LAST:event_MojProfilProdavacActionPerformed

    private void OdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OdjavaActionPerformed
        Kupac.setUlogovan(false);
        Prodavac.setUlogovan(false);
        this.Switch(new Odjavljivanje(this));
    }//GEN-LAST:event_OdjavaActionPerformed

    private void MojiApartmaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MojiApartmaniActionPerformed
        this.Switch(new PretragaApartmanaProdavac(this));
    }//GEN-LAST:event_MojiApartmaniActionPerformed

    private void ApartmaniLokacijaProdavacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApartmaniLokacijaProdavacActionPerformed
        this.Switch(new PretragaApartmanaLokacija(this));
    }//GEN-LAST:event_ApartmaniLokacijaProdavacActionPerformed

    private void ApartmaniLokacijaKupacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApartmaniLokacijaKupacActionPerformed
        this.Switch(new PretragaApartmanaLokacija(this));
    }//GEN-LAST:event_ApartmaniLokacijaKupacActionPerformed

    private void MojeRezervacijeProdavacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MojeRezervacijeProdavacActionPerformed
        this.Switch(new PregledRezervacijaProdavac(this));
    }//GEN-LAST:event_MojeRezervacijeProdavacActionPerformed

    private void MojeRezervacijeKupacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MojeRezervacijeKupacActionPerformed
        this.Switch(new PregledRezervacijaKupac(this));
    }//GEN-LAST:event_MojeRezervacijeKupacActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SAB_Projekat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SAB_Projekat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SAB_Projekat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SAB_Projekat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SAB_Projekat().setVisible(true);
            }
        });
    }

    public void Switch(JPanel panel) {

        this.getContentPane().remove(this.HomePanel);
        this.HomePanel = panel;
        this.getContentPane().add(this.HomePanel);
        validate();
        this.HomePanel.setVisible(true);
        setVisible(true);

    }

    public JMenuItem getApartmaniLokacijaKupac() {
        return ApartmaniLokacijaKupac;
    }

    public JMenuItem getApartmaniLokacijaProdavac() {
        return ApartmaniLokacijaProdavac;
    }

    public JPanel getHomePanel() {
        return HomePanel;
    }

    public JMenu getKupacB() {
        return KupacB;
    }

    public JMenu getProdavacB() {
        return ProdavacB;
    }

    public JMenu getLogin() {
        return Login;
    }

    public JMenuItem getLoginKupac() {
        return LoginKupac;
    }

    public JMenuItem getLoginProdavac() {
        return LoginProdavac;
    }

    public JMenu getMojProfil() {
        return MojProfil;
    }

    public JMenuItem getMojProfilKupac() {
        return MojProfilKupac;
    }

    public JMenuItem getMojProfilProdavac() {
        return MojProfilProdavac;
    }

    public JMenuItem getMojiApartmani() {
        return MojiApartmani;
    }

    public JMenuItem getOdjava() {
        return Odjava;
    }

    public JMenu getOdjavljivanje() {
        return Odjavljivanje;
    }

    public JMenu getRegistracija() {
        return Registracija;
    }

    public JMenuItem getRegistracijaKupac() {
        return RegistracijaKupac;
    }

    public JMenuItem getRegistracijaProdavac() {
        return RegistracijaProdavac;
    }

    public JMenu getjMenu4() {
        return MojProfil;
    }

    public JMenu getjMenu5() {
        return ProdavacB;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public JMenuItem getjMenuItem1() {
        return jMenuItem1;
    }

    public JMenuItem getjMenuItem11() {
        return MojeRezervacijeKupac;
    }

    public JMenuItem getjMenuItem6() {
        return MojeRezervacijeProdavac;
    }

    public JMenuItem getjMenuItem7() {
        return jMenuItem7;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ApartmaniLokacijaKupac;
    private javax.swing.JMenuItem ApartmaniLokacijaProdavac;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JMenu KupacB;
    private javax.swing.JMenu Login;
    private javax.swing.JMenuItem LoginKupac;
    private javax.swing.JMenuItem LoginProdavac;
    private javax.swing.JMenu MojProfil;
    private javax.swing.JMenuItem MojProfilKupac;
    private javax.swing.JMenuItem MojProfilProdavac;
    private javax.swing.JMenuItem MojeRezervacijeKupac;
    private javax.swing.JMenuItem MojeRezervacijeProdavac;
    private javax.swing.JMenuItem MojiApartmani;
    private javax.swing.JMenuItem Odjava;
    private javax.swing.JMenu Odjavljivanje;
    private javax.swing.JMenu ProdavacB;
    private javax.swing.JMenu Registracija;
    private javax.swing.JMenuItem RegistracijaKupac;
    private javax.swing.JMenuItem RegistracijaProdavac;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem7;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
