/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sab_grafika;

import java.awt.CardLayout;
import javax.swing.JPanel;
import sab_implementacija.Kupac;
import sab_implementacija.Prodavac;

/**
 *
 * @author Marija
 */
public class SAB_Projekat extends javax.swing.JFrame {

    /**
     * Creates new form SAB_Projekat
     */
    public SAB_Projekat() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        HomePanel = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jMenuBar1 = new javax.swing.JMenuBar();
        Login = new javax.swing.JMenu();
        LoginKupac = new javax.swing.JMenuItem();
        LoginProdavac = new javax.swing.JMenuItem();
        Registracija = new javax.swing.JMenu();
        RegistracijaKupac = new javax.swing.JMenuItem();
        RegistracijaProdavac = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MojProfilKupac = new javax.swing.JMenuItem();
        MojProfilProdavac = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        Odjavljivanje = new javax.swing.JMenu();
        Odjava = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        HomePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 153, 153)));

        label1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        label1.setText("SAB_Projekat");

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(344, Short.MAX_VALUE))
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        getContentPane().add(HomePanel);

        Login.setText("Logovanje");

        LoginKupac.setText("Kupac");
        LoginKupac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginKupacActionPerformed(evt);
            }
        });
        Login.add(LoginKupac);

        LoginProdavac.setText("Prodavac");
        LoginProdavac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginProdavacActionPerformed(evt);
            }
        });
        Login.add(LoginProdavac);

        jMenuBar1.add(Login);

        Registracija.setText("Registracija");

        RegistracijaKupac.setText("Kupac");
        RegistracijaKupac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistracijaKupacActionPerformed(evt);
            }
        });
        Registracija.add(RegistracijaKupac);

        RegistracijaProdavac.setText("Prodavac");
        RegistracijaProdavac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistracijaProdavacActionPerformed(evt);
            }
        });
        Registracija.add(RegistracijaProdavac);

        jMenuBar1.add(Registracija);

        jMenu4.setText("Moj profil");

        MojProfilKupac.setText("Kupac");
        MojProfilKupac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MojProfilKupacActionPerformed(evt);
            }
        });
        jMenu4.add(MojProfilKupac);

        MojProfilProdavac.setText("Prodavac");
        MojProfilProdavac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MojProfilProdavacActionPerformed(evt);
            }
        });
        jMenu4.add(MojProfilProdavac);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Prodavac");

        jMenuItem5.setText("Moji apartmani");
        jMenu5.add(jMenuItem5);

        jMenuItem6.setText("Moje rezervacije");
        jMenu5.add(jMenuItem6);

        jMenuItem7.setText("Dodaj apartman");
        jMenu5.add(jMenuItem7);

        jMenuItem8.setText("Dodaj sobu");
        jMenu5.add(jMenuItem8);

        jMenuBar1.add(jMenu5);

        jMenu3.setText("Kupac");

        jMenuItem11.setText("Moje rezervacije");
        jMenu3.add(jMenuItem11);

        jMenuBar1.add(jMenu3);

        Odjavljivanje.setText("Odjavi se");

        Odjava.setText("Odjavi se");
        Odjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OdjavaActionPerformed(evt);
            }
        });
        Odjavljivanje.add(Odjava);

        jMenuBar1.add(Odjavljivanje);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistracijaProdavacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistracijaProdavacActionPerformed

        Switch(new RegistracijaProdavca(this));
    }//GEN-LAST:event_RegistracijaProdavacActionPerformed

    private void RegistracijaKupacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistracijaKupacActionPerformed

        Switch(new RegistracijaKupca(this));
    }//GEN-LAST:event_RegistracijaKupacActionPerformed

    private void MojProfilKupacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MojProfilKupacActionPerformed
        Switch(new MojProfilKupac(this));
    }//GEN-LAST:event_MojProfilKupacActionPerformed

    private void LoginProdavacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginProdavacActionPerformed
        Switch(new LoginProdavca(this));
    }//GEN-LAST:event_LoginProdavacActionPerformed

    private void LoginKupacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginKupacActionPerformed
        Switch(new LoginKupca(this));

    }//GEN-LAST:event_LoginKupacActionPerformed

    private void MojProfilProdavacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MojProfilProdavacActionPerformed
        Switch(new MojProfilProdavac(this));
    }//GEN-LAST:event_MojProfilProdavacActionPerformed

    private void OdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OdjavaActionPerformed
        Kupac.setUlogovan(false);
        Prodavac.setUlogovan(false);
        this.Switch(new Odjavljivanje());
    }//GEN-LAST:event_OdjavaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SAB_Projekat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SAB_Projekat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SAB_Projekat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SAB_Projekat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SAB_Projekat().setVisible(true);
            }
        });
    }

    public void Switch(JPanel panel) {

        this.getContentPane().remove(this.HomePanel);
        this.HomePanel = panel;
        this.getContentPane().add(this.HomePanel);
        validate();
        this.HomePanel.setVisible(true);
        setVisible(true);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HomePanel;
    private javax.swing.JMenu Login;
    private javax.swing.JMenuItem LoginKupac;
    private javax.swing.JMenuItem LoginProdavac;
    private javax.swing.JMenuItem MojProfilKupac;
    private javax.swing.JMenuItem MojProfilProdavac;
    private javax.swing.JMenuItem Odjava;
    private javax.swing.JMenu Odjavljivanje;
    private javax.swing.JMenu Registracija;
    private javax.swing.JMenuItem RegistracijaKupac;
    private javax.swing.JMenuItem RegistracijaProdavac;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
