/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sab_grafika;

import sab_implementacija.Apartman;
import sab_implementacija.Soba;

/**
 *
 * @author Marija
 */
public class UredjivanjeApartmana extends javax.swing.JPanel {

    private SAB_Projekat Home;
    private Integer IDApartman;

    /**
     * Creates new form UredjivanjeApartmana
     */
    public UredjivanjeApartmana(SAB_Projekat Home, Integer IDApartman) {
        initComponents();
        this.Home = Home;
        this.IDApartman = IDApartman;
        Apartman apt = Apartman.dohvatiApartman(IDApartman);

        this.NazivApartmana.setText(apt.getNaziv());
        this.OpisApartmana.setText(apt.getOpis());

        String ispis = "Sobe:\n";
        

        ispis += Soba.sobeApartman(IDApartman);

        this.SobeApartman.setText(ispis);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        NazivApartmana = new javax.swing.JTextField();
        RedniBroj = new javax.swing.JTextField();
        BrojOsoba = new javax.swing.JTextField();
        RBSobe = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        SobeApartman = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Dodaj = new javax.swing.JButton();
        Obrisi = new javax.swing.JButton();
        Izmeni = new javax.swing.JButton();
        Zakljucaj = new javax.swing.JButton();
        OpisSobe = new javax.swing.JTextField();
        OpisApartmana = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        IzmeniApartman = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Otkljucaj = new javax.swing.JButton();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setMinimumSize(new java.awt.Dimension(1600, 600));
        setPreferredSize(new java.awt.Dimension(1600, 600));

        RBSobe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBSobeActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(SobeApartman);

        jLabel1.setText(" Naziv apartmana:");

        jLabel2.setText("Redni broj:");

        jLabel3.setText("Opis:");

        jLabel4.setText("Broj osoba:");

        Dodaj.setText("Dodaj");
        Dodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DodajActionPerformed(evt);
            }
        });

        Obrisi.setText("Obrisi");
        Obrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObrisiActionPerformed(evt);
            }
        });

        Izmeni.setText("Izmeni");
        Izmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IzmeniActionPerformed(evt);
            }
        });

        Zakljucaj.setText("Zakljucaj");
        Zakljucaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZakljucajActionPerformed(evt);
            }
        });

        jLabel5.setText("Opis apartmana");

        IzmeniApartman.setText("Izmeni apartman");
        IzmeniApartman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IzmeniApartmanActionPerformed(evt);
            }
        });

        jLabel6.setText("Unesite redni broj sobe sa kojom zelite da radite za operacije dodaj, izmeni i zakljucaj/otkljucaj");

        Otkljucaj.setText("Otkljucaj");
        Otkljucaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtkljucajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(OpisApartmana, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                            .addComponent(NazivApartmana))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IzmeniApartman)
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RedniBroj)
                            .addComponent(OpisSobe)
                            .addComponent(BrojOsoba)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RBSobe, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(Dodaj)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Obrisi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Izmeni)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Zakljucaj)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Otkljucaj)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NazivApartmana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OpisApartmana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IzmeniApartman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(RBSobe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Dodaj)
                            .addComponent(Obrisi)
                            .addComponent(Izmeni)
                            .addComponent(Zakljucaj)
                            .addComponent(Otkljucaj))
                        .addGap(52, 52, 52)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RedniBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(BrojOsoba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OpisSobe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void IzmeniApartmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IzmeniApartmanActionPerformed
        Apartman.izmeniApartman(IDApartman, this.NazivApartmana.getText(), this.OpisApartmana.getText());
        Apartman apt = Apartman.dohvatiApartman(IDApartman);
        this.NazivApartmana.setText(apt.getNaziv());
        this.OpisApartmana.setText(apt.getOpis());


    }//GEN-LAST:event_IzmeniApartmanActionPerformed

    private void RBSobeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBSobeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBSobeActionPerformed

    private void ZakljucajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZakljucajActionPerformed
        Integer IDSoba = Soba.dohvatiIDSobe(Integer.parseInt(this.RBSobe.getText()), IDApartman);
        String ispis = "Sobe:\n";
        if (IDSoba != 0) {
            Soba.zakljucaj(IDSoba);

            ispis += Soba.sobeApartman(IDApartman);
        } else {
            ispis = "Niste uneli validan redni broj sobe ";
        }

        this.SobeApartman.setText(ispis);
    }//GEN-LAST:event_ZakljucajActionPerformed

    private void OtkljucajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtkljucajActionPerformed

        Integer IDSoba = Soba.dohvatiIDSobe(Integer.parseInt(this.RBSobe.getText()), IDApartman);
        String ispis = "Sobe:\n";
        if (IDSoba != 0) {
            Soba.otkljucaj(IDSoba);

            ispis += Soba.sobeApartman(IDApartman);
        } else {
            ispis = "Niste uneli validan redni broj sobe ";
        }

        this.SobeApartman.setText(ispis);
    }//GEN-LAST:event_OtkljucajActionPerformed

    private void DodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DodajActionPerformed

        Soba.dodajSobu(IDApartman, Integer.parseInt(this.RedniBroj.getText()), Integer.parseInt(this.BrojOsoba.getText()), this.OpisSobe.getText());
        String ispis = "Sobe:\n";

        ispis += Soba.sobeApartman(IDApartman);

        this.SobeApartman.setText(ispis);
    }//GEN-LAST:event_DodajActionPerformed

    private void ObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObrisiActionPerformed

        Integer IDSoba = Soba.dohvatiIDSobe(Integer.parseInt(this.RBSobe.getText()), IDApartman);
        String ispis = "Sobe:\n";
        if (IDSoba != 0) {
            Soba.obrisiSobu(IDSoba);

            ispis += Soba.sobeApartman(IDApartman);
        } else {
            ispis = "Niste uneli validan redni broj sobe ";
        }

        this.SobeApartman.setText(ispis);
    }//GEN-LAST:event_ObrisiActionPerformed

    private void IzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IzmeniActionPerformed

        Integer IDSoba = Soba.dohvatiIDSobe(Integer.parseInt(this.RBSobe.getText()), IDApartman);
        String ispis = "Sobe:\n";
        if (IDSoba != 0) {
            Soba.izmeniSobu(IDSoba, Integer.parseInt(this.RedniBroj.getText()), Integer.parseInt(this.BrojOsoba.getText()), this.OpisSobe.getText());

            ispis += Soba.sobeApartman(IDApartman);

        } else {
            ispis = "Niste uneli validan redni broj sobe ";
        }

        this.SobeApartman.setText(ispis);
    }//GEN-LAST:event_IzmeniActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BrojOsoba;
    private javax.swing.JButton Dodaj;
    private javax.swing.JButton Izmeni;
    private javax.swing.JButton IzmeniApartman;
    private javax.swing.JTextField NazivApartmana;
    private javax.swing.JButton Obrisi;
    private javax.swing.JTextField OpisApartmana;
    private javax.swing.JTextField OpisSobe;
    private javax.swing.JButton Otkljucaj;
    private javax.swing.JTextField RBSobe;
    private javax.swing.JTextField RedniBroj;
    private javax.swing.JEditorPane SobeApartman;
    private javax.swing.JButton Zakljucaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
